server:
  port: ${SERVER_PORT:8200}

spring:
  application:
    name: medical-record-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/local_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: medical_record
  liquibase:
    default-schema: medical_record

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}