logging:
  level:
    org:
      springframework:
        cloud.gateway: TRACE
        web.servlet.function: TRACE

management:
  endpoint:
    health:
      show-details: always

server:
  port: ${SERVER_PORT:8000}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          x-forwarded-request-headers-filter:
            enabled: false

          # match any private / public address
          trusted-proxies: '(?:"?((?:\b\d{1,3}(?:\.\d{1,3}){3}\b)|(?:\[[0-9a-fA-F:]+\])|(?:\b[0-9a-fA-F:]+\b))"?)'

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

routing:
  routes:
    user-service: /usr
    appointment-service: /appt
    payment-service: /pay

cors:
  registry:
    "[/**]":
      allow-credentials: true
      allowed-origin-patterns: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      exposed-headers: "Access-Control-Allow-Origin"
