logging:
  level:
    org:
      springframework:
        cloud.gateway: TRACE
        web.servlet.function: TRACE
        security: TRACE
    com.medtech.gateway.config.filter: DEBUG

management:
  endpoint:
    health:
      show-details: always

server:
  port: ${SERVER_PORT:8000}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          x-forwarded-request-headers-filter:
            enabled: false

          # match any private / public address
          trusted-proxies: '(?:"?((?:\b\d{1,3}(?:\.\d{1,3}){3}\b)|(?:\[[0-9a-fA-F:]+\])|(?:\b[0-9a-fA-F:]+\b))"?)'
  security:
    oauth2:
      client:
        registration:
          ms-gateway:
            provider: ${GATEWAY_OAUTH2_CLIENT_PROVIDER:keycloak}
            client-id: ${GATEWAY_OAUTH2_CLIENT_ID:2e970c95-cee6-4183-99ff-7b944dbd02db}
            client-secret: ${GATEWAY_OAUTH2_CLIENT_SECRET:hPTNDhazLNGikvrNcwxYeaAQrWVVwu5J}
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: ${GATEWAY_OAUTH2_CLIENT_ISSUER_URI:http://localhost:9000/realms/medsync}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  session:
    redis:
      namespace: spring:session:gateway
      repository-type: default

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

routing:
  routes:
    user-service: /usr
    appointment-service: /appt
    payment-service: /pay

cors:
  registry:
    "[/**]":
      allow-credentials: true
      allowed-origin-patterns: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      exposed-headers: "Access-Control-Allow-Origin"
