spring:
  application:
    name: discovery-service
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoint:
    health:
      show-details: always

server:
  port: ${SERVER_PORT:8761}





