server:
  port: ${SERVER_PORT:8300}

spring:
  application:
    name: appointment-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    open-in-view: false